package ArsenyVekshin.lab7.common.annotations;

/**
 * Class that validate that fields value is autogenerated
 */
public class AutoGeneratedValidator implements Validatable {
    private static AutoGeneratedValidator instance;

    public <T> boolean validate(T value) throws IllegalArgumentException {
        return true;
    }

    public AutoGeneratedValidator getInstance() {
        if(instance == null) {
            instance = new AutoGeneratedValidator();
        }
        return instance;
    }
}