package ArsenyVekshin.lab5.collection.data;

import ArsenyVekshin.lab5.collection.CSVOperator;
import ArsenyVekshin.lab5.collection.exceptions.*;
import ArsenyVekshin.lab5.utils.validators.AutoGenerated;
import ArsenyVekshin.lab5.utils.validators.GreaterThan;
import ArsenyVekshin.lab5.utils.validators.NotNull;
import ArsenyVekshin.lab5.utils.validators.StringNotNone;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Objects;
import java.util.function.Supplier;


public class Product implements Cloneable, CSVOperator {
    @NotNull
    @GreaterThan("0")
    @AutoGenerated
    private int id; //Поле не может быть null, Значение поля должно быть больше 0, Значение этого поля должно быть уникальным, Значение этого поля должно генерироваться автоматически
    @NotNull
    @StringNotNone
    private String name; //Поле не может быть null, Строка не может быть пустой
    @NotNull
    private Coordinates coordinates; //Поле не может быть null

    @NotNull
    @AutoGenerated
    private LocalDate creationDate; //Поле не может быть null, Значение этого поля должно генерироваться автоматически
    @GreaterThan("0")
    private float price; //Значение поля должно быть больше 0
    private UnitOfMeasure unitOfMeasure; //Поле может быть null
    private Organization manufacturer; //Поле может быть null

    public Product(){}

    public Product(int id, String name, Coordinates coordinates, float price, UnitOfMeasure unitOfMeasure, Organization manufacturer){
        this.id = id; //генерируется вне объекта из глобального счетчика
        creationDate = LocalDate.from(LocalDateTime.now());
        try {
            setName(name);
            setCoordinates(coordinates);
            setPrice(price);
            setUnitOfMeasure(unitOfMeasure);
            setManufacturer(manufacturer);
        }
        catch (InvalidValueEntered e){
            System.out.println(e.getMessage());
        }
    }
    public Product(HashMap<String, Object> tree){
        genByTree(tree);
    }

    public void genByTree(HashMap<String, Object> tree){
        if(tree.containsKey("id")) setId((int)tree.get("id"));

        if(tree.containsKey("creationDate")) creationDate = (LocalDate)tree.get("creationDate");
        else creationDate = LocalDate.from(LocalDateTime.now());

        name = (String) tree.get("name");
        coordinates = (Coordinates) tree.get("coordinates");
        price = (float) tree.get("price");
        unitOfMeasure = (UnitOfMeasure) tree.get("unitOfMeasure");
        manufacturer = (Organization) tree.get("manufacturer");
    }

    public void generateID(int counter){
        setId(counter);
        manufacturer.setId(counter + Integer.MAX_VALUE);
    }
    public void setId(int id){
        this.id = id;
    }
    public int getId() {
        return id;
    }


    public String getName() {
        return name;
    }

    public void setName(String name) throws InvalidValueEntered {
        if (name == null || name.length()==0) {
            this.name = "default";
            throw new InvalidValueEntered(this.getClass().getName(), "name");
        }
        else this.name = name;
    }

    public Coordinates getCoordinates() {
        return coordinates;
    }

    public void setCoordinates(Coordinates coordinates) throws InvalidValueEntered {
        if (coordinates == null) {
            this.coordinates = new Coordinates(0,0);
            throw new InvalidValueEntered(this.getClass().getName(), "coordinates");
        }
        else this.coordinates = coordinates;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) throws InvalidValueEntered {
        if (price <=0) {
            this.price = 1;
            throw new InvalidValueEntered(this.getClass().getName(), "price");
        }
        else this.price = price;
    }

    public UnitOfMeasure getUnitOfMeasure() {
        return unitOfMeasure;
    }

    public void setUnitOfMeasure(UnitOfMeasure unitOfMeasure) throws InvalidValueEntered {
        if (unitOfMeasure == null) {
            this.unitOfMeasure = UnitOfMeasure.DEFAULT;
            throw new InvalidValueEntered(this.getClass().getName(), "unitOfMeasure");
        }
        else this.unitOfMeasure = unitOfMeasure;
    }

    public Organization getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(Organization manufacturer) throws InvalidValueEntered {
        if (manufacturer == null) throw new InvalidValueEntered(this.getClass().getName(), "manufacter");
        else this.manufacturer = manufacturer;
    }


    public LocalDate getCreationDate() {
        return creationDate;
    }

    public Product clone() throws CloneNotSupportedException {
        return (Product) super.clone();
    }

    public Supplier<Product> getConstructorReference() {
        return Product::new;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name,coordinates, creationDate, price, unitOfMeasure, manufacturer);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Product check = (Product) o;
        return hashCode() == check.hashCode();
    }

    @Override
    public String toString(){
        return "Product(" +
                "id=" + id +
                ", name=" + name +
                ", coordinates=" + coordinates.toString() +
                ", creationDate=" + creationDate.format(DateTimeFormatter.ofPattern("HH:mm:ss dd/MM/yyyy")) +
                ", price=" + price +
                ", unitOfMeasure=" + unitOfMeasure +
                ", manufacturer=" + manufacturer.toString() + ");";
    }

    @Override
    public String generateCSV() {
        return id +
                ", " + name +
                ", " + coordinates.generateCSV() +
                ", " + creationDate.format(DateTimeFormatter.ofPattern("HH:mm:ss dd/MM/yyyy")) +
                ", " + price +
                ", " + unitOfMeasure +
                ", " + manufacturer.generateCSV();
    }
}


