package ArsenyVekshin.lab5.utils.validators;

import java.lang.annotation.*;

/**
 * this field generates automatically
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Documented
@ValidatableAnnotation(validator = AutoGeneratedValidator.class)
public @interface AutoGenerated {
}
